theme = "dracula"

[editor]
true-color = true
line-number = "relative"
rulers = [100]

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
tabpad = "all"
newline = "none"

[editor.soft-wrap]
enable = true
